export const twTypeStyles = {
    ".text-hero": {
        fontSize: "var(--fontSizes-7)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tighter)",
    },
    ".text-headline": {
        fontSize: "var(--fontSizes-6)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tighter)",
    },
    ".text-title1": {
        fontSize: "var(--fontSizes-5)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tight)",
    },
    ".text-title2": {
        fontSize: "var(--fontSizes-4)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tight)",
    },
    ".text-title3": {
        fontSize: "var(--fontSizes-3)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tight)",
    },
    ".text-heading": {
        fontSize: "var(--fontSizes-2)",
        lineHeight: "var(--lineHeights-tight)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-tight)",
    },
    ".text-subhead": {
        fontSize: "var(--fontSizes-1)",
        fontFamily: "var(--fonts-display)",
        fontWeight: "var(--fontWeights-heavy)",
        letterSpacing: "var(--letterSpacings-normal)",
    },
    ".text-body": {
        fontSize: "var(--fontSizes-0)",
        fontFamily: "var(--fonts-text)",
        letterSpacing: "var(--letterSpacings-normal)",
    },
    ".text-footnote": {
        fontSize: "var(--fontSizes--1)",
        fontFamily: "var(--fonts-text)",
        letterSpacing: "var(--letterSpacings-wide)",
    },
    ".text-caption": {
        fontSize: "var(--fontSizes--2)",
        fontFamily: "var(--fonts-text)",
    },
    ".text-micro": {
        fontSize: "var(--fontSizes--3)",
        fontFamily: "var(--fonts-text)",
    },
};

export const twTheme = {
    colors: {
        transparent: "transparent",
        white: "var(--colors-white)",
        black: "var(--colors-black)",

        primary: {
            brand: "var(--colors-primaryBrand)",
            midnight: "var(--colors-primaryMidnight)",
        },

        accent: {
            amber: "var(--colors-accentAmber)",
            orange: "var(--colors-accentOrange)",
            red: "var(--colors-accentRed)",
            plum: "var(--colors-accentPlum)",
            blue: "var(--colors-accentBlue)",
            sky: "var(--colors-accentSky)",
            teal: "var(--colors-accentTeal)",
            green: "var(--colors-accentGreen)",
        },

        slate: {
            1: "var(--colors-slate1)",
            2: "var(--colors-slate2)",
            3: "var(--colors-slate3)",
            4: "var(--colors-slate4)",
            5: "var(--colors-slate5)",
            6: "var(--colors-slate6)",
            7: "var(--colors-slate7)",
            8: "var(--colors-slate8)",
            9: "var(--colors-slate9)",
            10: "var(--colors-slate10)",
            11: "var(--colors-slate11)",
            12: "var(--colors-slate12)",
        },
        amber: {
            1: "var(--colors-amber1)",
            2: "var(--colors-amber2)",
            3: "var(--colors-amber3)",
            4: "var(--colors-amber4)",
            5: "var(--colors-amber5)",
            6: "var(--colors-amber6)",
            7: "var(--colors-amber7)",
            8: "var(--colors-amber8)",
            9: "var(--colors-amber9)",
            10: "var(--colors-amber10)",
            11: "var(--colors-amber11)",
            12: "var(--colors-amber12)",
        },
        red: {
            1: "var(--colors-red1)",
            2: "var(--colors-red2)",
            3: "var(--colors-red3)",
            4: "var(--colors-red4)",
            5: "var(--colors-red5)",
            6: "var(--colors-red6)",
            7: "var(--colors-red7)",
            8: "var(--colors-red8)",
            9: "var(--colors-red9)",
            10: "var(--colors-red10)",
            11: "var(--colors-red11)",
            12: "var(--colors-red12)",
        },
        plum: {
            1: "var(--colors-plum1)",
            2: "var(--colors-plum2)",
            3: "var(--colors-plum3)",
            4: "var(--colors-plum4)",
            5: "var(--colors-plum5)",
            6: "var(--colors-plum6)",
            7: "var(--colors-plum7)",
            8: "var(--colors-plum8)",
            9: "var(--colors-plum9)",
            10: "var(--colors-plum10)",
            11: "var(--colors-plum11)",
            12: "var(--colors-plum12)",
        },
        indigo: {
            1: "var(--colors-indigo1)",
            2: "var(--colors-indigo2)",
            3: "var(--colors-indigo3)",
            4: "var(--colors-indigo4)",
            5: "var(--colors-indigo5)",
            6: "var(--colors-indigo6)",
            7: "var(--colors-indigo7)",
            8: "var(--colors-indigo8)",
            9: "var(--colors-indigo9)",
            10: "var(--colors-indigo10)",
            11: "var(--colors-indigo11)",
            12: "var(--colors-indigo12)",
        },
        blue: {
            1: "var(--colors-blue1)",
            2: "var(--colors-blue2)",
            3: "var(--colors-blue3)",
            4: "var(--colors-blue4)",
            5: "var(--colors-blue5)",
            6: "var(--colors-blue6)",
            7: "var(--colors-blue7)",
            8: "var(--colors-blue8)",
            9: "var(--colors-blue9)",
            10: "var(--colors-blue10)",
            11: "var(--colors-blue11)",
            12: "var(--colors-blue12)",
        },
        sky: {
            1: "var(--colors-sky1)",
            2: "var(--colors-sky2)",
            3: "var(--colors-sky3)",
            4: "var(--colors-sky4)",
            5: "var(--colors-sky5)",
            6: "var(--colors-sky6)",
            7: "var(--colors-sky7)",
            8: "var(--colors-sky8)",
            9: "var(--colors-sky9)",
            10: "var(--colors-sky10)",
            11: "var(--colors-sky11)",
            12: "var(--colors-sky12)",
        },
        teal: {
            1: "var(--colors-teal1)",
            2: "var(--colors-teal2)",
            3: "var(--colors-teal3)",
            4: "var(--colors-teal4)",
            5: "var(--colors-teal5)",
            6: "var(--colors-teal6)",
            7: "var(--colors-teal7)",
            8: "var(--colors-teal8)",
            9: "var(--colors-teal9)",
            10: "var(--colors-teal10)",
            11: "var(--colors-teal11)",
            12: "var(--colors-teal12)",
        },
        green: {
            1: "var(--colors-green1)",
            2: "var(--colors-green2)",
            3: "var(--colors-green3)",
            4: "var(--colors-green4)",
            5: "var(--colors-green5)",
            6: "var(--colors-green6)",
            7: "var(--colors-green7)",
            8: "var(--colors-green8)",
            9: "var(--colors-green9)",
            10: "var(--colors-green10)",
            11: "var(--colors-green11)",
            12: "var(--colors-green12)",
        },
        orange: {
            1: "var(--colors-orange1)",
            2: "var(--colors-orange2)",
            3: "var(--colors-orange3)",
            4: "var(--colors-orange4)",
            5: "var(--colors-orange5)",
            6: "var(--colors-orange6)",
            7: "var(--colors-orange7)",
            8: "var(--colors-orange8)",
            9: "var(--colors-orange9)",
            10: "var(--colors-orange10)",
            11: "var(--colors-orange11)",
            12: "var(--colors-orange12)",
        },

        // deprecated colours
        neutral: {
            100: "var(--colors-neutral100)",
            200: "var(--colors-neutral200)",
            300: "var(--colors-neutral300)",
            400: "var(--colors-neutral400)",
            500: "var(--colors-neutral500)",
            600: "var(--colors-neutral600)",
            700: "var(--colors-neutral700)",
            800: "var(--colors-neutral800)",
            900: "var(--colors-neutral900)",
        },
        midnight: {
            100: "var(--colors-midnight100)",
            300: "var(--colors-midnight300)",
            500: "var(--colors-midnight500)",
            700: "var(--colors-midnight700)",
            900: "var(--colors-midnight900)",
        },
    },
    fontSize: {
        "-3": "var(--step--3)",
        "-2": "var(--step--2)",
        "-1": "var(--step--1)",
        0: "var(--step-0)",
        1: "var(--step-1)",
        2: "var(--step-2)",
        3: "var(--step-3)",
        4: "var(--step-4)",
        5: "var(--step-5)",
        6: "var(--step-6)",
        7: "var(--step-7)",
    },
    fontFamily: {
        display: "var(--fonts-display)",
        text: "var(--fonts-text)",
        sans: "var(--fonts-text)",
    },
    lineHeight: {
        DEFAULT: "var(--lineHeights-normal)",
        tighter: "var(--lineHeights-xtight)",
        tight: "var(--lineHeights-tight)",
        normal: "var(--lineHeights-normal)",
        wide: "var(--lineHeights-loose)",
    },
    fontWeight: {
        DEFAULT: "var(--fontWeights-standard)",
        standard: "var(--fontWeights-standard)",
        heavy: "var(--fontWeights-heavy)",
    },
    letterSpacing: {
        tightest: "var(--letterSpacings-tightest)",
        tighter: "var(--letterSpacings-tighter)",
        tight: "var(--letterSpacings-tight)",
        normal: "var(--letterSpacings-normal)",
        wide: "var(--letterSpacings-wide)",
        wider: "var(--letterSpacings-wider)",
        widest: "var(--letterSpacings-widest)",
    },
    spacing: {
        0: "0rem",
        0.5: "0.25rem", // 4px
        1: "0.5rem", // 8px
        2: "1rem", // 16px
        3: "1.5rem", // 24px
        4: "2rem", // 32px
        5: "2.5rem", // 40px
        6: "3rem", // 48px
        7: "3.5rem", // 56px
        8: "4rem", // 64px
        9: "4.5rem", // 72px
        10: "10rem", // 80px
    },
    screens: {
        xs: "0",
        sm: "48rem", // 768
        md: "64rem", // 1024
        lg: "80rem", // 1280
        xl: "90rem", // 1440
    },
    extend: {},
};
